# Site settings
title: Stefan Popov
email: stebp.vn@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, I'm Stefan, and when I'm not coding little silly things, 
  I like to tinker with programs and computers. Currently 
  wolfing down Lengyel's Mathematics for Computer Graphics.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://stfnppv.github.io" # the base hostname & protocol for your site
twitter_username: stfnpopopop
github_username:  stfnppv

# Landing page
heroImage: "hero_sm.jpeg"
heroTitle: "Stefan Popov"

# About page
aboutTitle: "Profile"
aboutSubtitle: "Details"
aboutText: >
  Hi, I'm Stefan, and I am a second year at the University of Chicago, 
  currently on a leave of absence. In my spare time, I like to program 
  small silly things and go through Computer Science books. This is the
  the part where I guess I am supposed to say how I am a "ninja coder",
  or "rockstar developer", or "simply badass" or whatever the newest silly 
  buzzword is; but the truth is I am just a person who loves to tinker 
  and solve puzzles. Be it actual kiddie puzzles I'd go through by the
  dozen when I was little, or the convoluted, obfuscated assembly code
  of an actual tarbomb I had to defuse in gdb for one of my classes 
  (best class project ever). If you would like to reach me, there are
  various ways to do so below.
aboutImage: "me.jpeg"

# Build settings
markdown: kramdown
