# Site settings
title: Stefan Popov
email: stebp.vn@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: stfnpopopop
github_username:  stfnppv

# Build settings
markdown: kramdown
highlighter: pygments